-- Deprecated.
--
-- The canonical row-level security definitions live in schema.sql. Existing
-- deployments should apply the versioned migrations in supabase/migrations.
-- This file intentionally contains no executable SQL so stale policies cannot
-- accidentally be restored.
